#ifndef __METRIS_METRIS__
#define __METRIS_METRIS__

#include "SurrealS_inc.hxx"
#include "aux_EGADSprinterr.hxx"
#include "aux_exceptions.hxx"
#include "aux_hashtab.hxx"
#include "aux_histogram.hxx"
#include "aux_topo.hxx"
#include "metris_constants.hxx"
#include "metris_defaults.hxx"
#include "codegen_ccoef.hxx"
#include "codegen_ccoef_d.hxx"
#include "codegen_lag2bez.hxx"
#include "codegen_lagrange.hxx"
#include "common_includes.hxx"
#include "ho_constants.hxx"
#include "ho_quadrature.hxx"
#include "inc_hana.hxx"
#include "io_libmeshb.hxx"
#include "low_eval.hxx"
#include "low_evalS.hxx"
#include "low_eval_d.hxx"
#include "low_eval_d_SurrealS.hxx"
#include "low_subdivide.hxx"
#include "low_topo.hxx"
#include "main_adap.hxx"
#include "metris_options.hxx"
#include "msh_Hilbert.hxx"
#include "msh_anamet.hxx"
#include "msh_checktopo.hxx"
#include "msh_degelev.hxx"
#include "msh_inineigh.hxx"
#include "msh_lag2bez.hxx"
#include "msh_lenedg.hxx"
#include "msh_structs.hxx"
#include "types.hxx"

#include "Optimization/opt_generic.hxx"

#include "low_geo/misc.hxx"
#include "low_geo/lenedg.hxx"
#include "low_geo/ccoef.hxx"
#include "low_geo/measure.hxx"
#include "low_geo/normal.hxx"
#include "low_geo/ccoef_d.hxx"

#include "utils/CT_loop.hxx"
#include "utils/aux_misc.hxx"
#include "utils/aux_pp_inc.hxx"
#include "utils/aux_timer.hxx"
#include "utils/bernstein_prod.hxx"
#include "utils/fact_pow.hxx"
#include "utils/mprintf.hxx"
#include "utils/fmt_formatters.hxx"

#include "API/MetrisAPI.hxx"
#include "Arrays/aux_msharrays.hxx"

#include "Boundary/low_geosurf.hxx"
#include "Boundary/low_projsurf.hxx"
#include "Boundary/msh_inisurf.hxx"

#include "LPopt/msh_maxccoef.hxx"

#include "Mesh/CADInfo.hxx"
#include "Mesh/Mesh.hxx"
#include "Mesh/MeshBack.hxx"
#include "Mesh/MeshBase.hxx"
#include "Mesh/MeshFwd.hxx"
#include "Mesh/MeshMetric.hxx"

#include "SolutionField/SolutionField.hxx"
#include "SolutionField/minInterpError.hxx"
#include "SolutionField/interpError.hxx"

#include "MetricField/MetricField.hxx"
#include "MetricField/msh_checkmet.hxx"
#include "MetricField/msh_explogmet.hxx"
#include "MetricField/msh_intrinsicmet.hxx"
#include "MetrisRunner/MetrisParameters.hxx"
#include "MetrisRunner/MetrisRunner.hxx"

#include "Adaptation/low_collapse.hxx"
#include "Adaptation/low_delaunay.hxx"
#include "Adaptation/low_increasecav.hxx"
#include "Adaptation/low_swap.hxx"
#include "Adaptation/msh_collapse.hxx"
#include "Adaptation/msh_lineadapt.hxx"
#include "Adaptation/msh_swap.hxx"
#include "Adaptation/Insertion/msh_insert.hxx"
#include "Adaptation/Insertion/low_insert.hxx"

#include "cavity/msh_cavity.hxx"

#include "linalg/det.hxx"
#include "linalg/dsyevq.hxx"
#include "linalg/dsytrd.hxx"
#include "linalg/eigen.hxx"
#include "linalg/explogmet.hxx"
#include "linalg/invmat.hxx"
#include "linalg/matprods.hxx"
#include "linalg/symidx.hxx"
#include "linalg/utils.hxx"

#include "Localization/low_localization.hxx"
#include "Localization/msh_localization.hxx"

#include "BezierOffsets/low_gaps.hxx"
#include "BezierOffsets/msh_bez2gaps.hxx"

#include "quality/low_metqua.hxx"
#include "quality/low_metqua_d.hxx"

#include "smoothing/low_smooballNewton.hxx"
#include "smoothing/low_smooballdiff.hxx"
#include "smoothing/msh_smooball.hxx"
#endif